# Generated by Django 3.2.7 on 2023-05-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='mainapp.user')),
            ],
        ),
    ]
